### ISSUE TITLE
Arduino Due compatibility

### ISSUE THREAD

**Issue by mattocastillo** [sparkfun/MPU-9250_Breakout#11]
I have an Arduino Due, when im compiling there is a warning message saying that the program architecture is SAMD and arduino DUE is SAM.
im trying to upload the example MPU9250_Basic
it compiles and the program runs, i can see the data on the Serial Monitor but it doesnt read correct data, all the sensors are in 0, or 0.6 in some cases.

i tried the same on an arduino leonardo and it works great with correct data.

what can i do to run it on an arduino due?

**Comment by santaimpersonator** [comment]
Unfortunately, the SAMD and SAM3 are [different](https://en.wikipedia.org/wiki/Atmel_ARM-based_processors). If you are using this [library](https://github.com/sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library), it is noted in the README.md that:

> "**This library currently only supports and is tested on SAMD processors**"

The MPU-9250 is EOL, so may not expand compatibility for other boards. You will probably need a logic level converter. Additionally, it seems like there are other resources online that have a compatibility with an Arduino Due ([see here](https://github.com/kriswiner/MPU9250/issues/58)).
