### ISSUE TITLE
What is the difference between these 3 libraries?

### ISSUE THREAD

**Issue by laurentvm** [sparkfun/MPU-9250_Breakout#15]
You are providing a library but we can found 3 others:
https://github.com/sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library
https://github.com/sparkfun/SparkFun_MPU-9250_Breakout_Arduino_Library

And also
https://github.com/kriswiner/MPU9250

What is the difference between them ?

**Comment by jimblom** [comment]
Hi @laurentvm,

This is a great question. We'll get a bit more documentation up to differentiate the SparkFun libraries.

* The [MPU-9250 Breakout Arduino Library](https://github.com/sparkfun/SparkFun_MPU-9250_Breakout_Arduino_Library) supports all basic sensor-reads (accel, mag, gyro) of the MPU-9250.
    * This library is forked from (based on) the [kriswiner/MPU9250](https://github.com/kriswiner/MPU9250) library, which performs similar operations.
* [The MPU-9250 DMP library](https://github.com/sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library) is a more advanced library which takes advantage of the MPU-9250's built-in digital-motion processor (DMP) and Invensense's library for the DMP. This provides access to the IMU's special features like a pedometer, tap-detection, quaternion- and orientation-calculation. This library is designed for more advanced microcontrollers -- it won't work with AVR's (e.g. Arduino Uno, SparkFun RedBoard, Arduino Mega) -- specifically the SAMD21 (see the [SparkFun 9DoF Razor IMU M0](https://www.sparkfun.com/products/14001) as an example).
