### ISSUE TITLE
Pull Up resistor

### ISSUE THREAD

**Issue by ShrutheeshIR** [sparkfun/MPU-9250_Breakout#16]
Hello. This is probably not the best place to ask this question, however I could not find the answer anywhere and I'm not able to get it working. Please feel free to delete/close this issue if inappropriate
I'm trying to connect this board to a software i2c on raspi, however after configuring the pins, it is not detected. 
Does this board have internal pull-up resistors, or do they have to be connected externally? 

Thanks

**Comment by lewispg228** [comment]
Hi @ShrutheeshIR ,
Sorry you are having trouble getting connected. Please post your issue on our forums and we'd be happy to help you further.

https://forum.sparkfun.com/viewtopic.php?f=59&t=49379

But to answer your question quickly. Yes, it does have pullups. You can always see the schematic of all SparkFun Products in the "documents" tab of the product page:

https://cdn.sparkfun.com/assets/c/7/8/f/8/15335_9DoF_Schematic.pdf

I would also like to suggest referencing our raspi I2C python support located here:

https://github.com/sparkfun/Qwiic_9DoF_IMU_ICM20948_Py

Have a great day and good luck!
-Pete

**Comment by ShrutheeshIR** [comment]
Hello @lewispg228 thank you for the swift response! 
Will certainly check out the Python code.

Thanks
