### ISSUE TITLE
Eagle Part for the MPU9250

### ISSUE THREAD

**Issue by worldwidemv** [sparkfun/MPU-9250_Breakout#9]
Hello,

first all nice board. I think this is the smallest one I have seen so far.
Anyway, I have a question about the exposed pad of the MPU9250.

You soldered it to GND. I know the Datasheet has no information what so ever about the pad, but according to https://store.invensense.com/datasheets/invensense/Accelerometer_Gyroscope_Design_Guidelines.pdf page 9 it should not be solder.

Maybe you have some more information from Invensense.
I would love to hear what you think.

Sincerely Markus

**Comment by santaimpersonator** [comment]
Unfortunately, that product is a little old and the original engineer has moved on to another company.

I am not absolutely sure, but we may have missed that information in the [Design Guidelines](https://store.invensense.com/datasheets/invensense/Accelerometer_Gyroscope_Design_Guidelines.pdf). It looks like that information cites package stress relief for omitting the EP. That being said, I don't think we have had many production issues with that board and the MPU-9250 is now EOL, so it is probably too late to make any changes now.
